### ISSUE TITLE
feature: allow many api connections

### ISSUE THREAD

**Issue by kouinkouin** [coopTilleuls/CoopTilleulsOvhBundle#15]
Hi,

In the configuration of the bundle (the yaml), is it possible to make something like that:
```yaml
coop_tilleuls_ovh:
    default: my-ovh
    connections:
        - my-ovh:
            endpoint_name:      "ovh-eu"
            application_key:    "%ovh_ak%"
            application_secret: "%ovh_as%"
            consumer_key:       "%ovh_ck%"
        - my-sys:
            endpoint_name:      "soyoustart-eu"
            application_key:    "%sys_ak%"
            application_secret: "%sys_as%"
            consumer_key:       "%sys_ck%"
        - my-ks:
            endpoint_name:      "kimsufi-eu"
            application_key:    "%ks_ak%"
            application_secret: "%ks_as%"
            consumer_key:       "%ks_ck%"
```

The `default` key is for one-instance usage.

That would permit to manage all ovh-group api's.

What do you think about that? Possible, out-of-scope bundle, over-engeneering?

Thanks in advance of your input.
