### ISSUE TITLE
Allow to pass a guzzle client service through this bundle

### ISSUE THREAD

**Issue by soullivaneuh** [coopTilleuls/CoopTilleulsOvhBundle#9]
As mentioned in https://github.com/coopTilleuls/CoopTilleulsOvhBundle/pull/7#issuecomment-278348984

The goal is just to make configuration easier. It is still doable with ease thanks to the compiler.

Example using [eightpoints/guzzle-bundle](https://packagist.org/packages/eightpoints/guzzle-bundle):

```yaml
eight_points_guzzle:
    clients:
        ovh:
            options:
                timeout: 20
```

```php
final class Kernel extends BaseKernel implements CompilerPassInterface
{
    use MicroKernelTrait;

    public function process(ContainerBuilder $container): void
    {
        $container->getDefinition('coop_tilleuls_ovh.api')
            ->addArgument(new Reference('eight_points_guzzle.client.ovh'));
    }
}
```
